// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF4IRX1zugs089BS4WGG8xffmj6ZNV464',
    appId: '1:1045910743865:web:337602c5acc461e3cdd6e8',
    messagingSenderId: '1045910743865',
    projectId: 'medicamina',
    authDomain: 'medicamina.firebaseapp.com',
    storageBucket: 'medicamina.appspot.com',
    measurementId: 'G-XEQJN78SR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtGJINMYstC5vW0M3SXIxn9vmA_kUVxKc',
    appId: '1:1045910743865:android:f97cfbfea5ce0f1acdd6e8',
    messagingSenderId: '1045910743865',
    projectId: 'medicamina',
    storageBucket: 'medicamina.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkjQBfO1C3MREG1iFnTGpMQuEIvZ9ROOA',
    appId: '1:1045910743865:ios:32deda01a4002e86cdd6e8',
    messagingSenderId: '1045910743865',
    projectId: 'medicamina',
    storageBucket: 'medicamina.appspot.com',
    iosBundleId: 'us.medicamina.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkjQBfO1C3MREG1iFnTGpMQuEIvZ9ROOA',
    appId: '1:1045910743865:ios:32deda01a4002e86cdd6e8',
    messagingSenderId: '1045910743865',
    projectId: 'medicamina',
    storageBucket: 'medicamina.appspot.com',
    iosBundleId: 'us.medicamina.app',
  );
}
